# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3eppGbTaSq_jww9oOekponbmUxckMKa

## Importing libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
import kagglehub

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.preprocessing import image


import numpy as np

# %matplotlib inline

"""## Importing Dataset From Kaggle




"""

# Download latest version
path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")

print("Path to dataset files:", path)

"""## Loading the Dataset"""

train_dir= path + '/Training'
test_dir= path + '/Testing'

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels='inferred',
    label_mode='int',
    color_mode='rgb',
    batch_size=32,
    image_size=(224, 224),
    shuffle=True,
    seed=42,
    validation_split=0.2,
    subset='training',
)

validation_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels='inferred',
    label_mode='int',
    color_mode='rgb',
    batch_size=32,
    image_size=(224, 224),
    shuffle=True,
    seed=42,
    validation_split=0.2,
    subset='validation',
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    labels='inferred',
    label_mode='int',
    color_mode='rgb',
    batch_size=32,
    image_size=(224, 224),
    shuffle=False,
    seed=42,
)

"""## Inspecting the Dataset
Checking the classes and a batch of images
"""

class_names = train_ds.class_names
print("Class names:", class_names)

for images, labels in train_ds.take(1):
    plt.figure(figsize=(10,10))
    for i in range(25):   # 25 images
        ax = plt.subplot(5, 5, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i].numpy()])
        plt.axis("off")

"""## Preprocessing


1.   Normalizing
2.   Data Augmentation


"""

#Normalizing ,scaling to 0-1 from 0-255.
normalising_layer = tf.keras.layers.Rescaling(1./255)

#Data Augmentation, i.e, artificially creating training data from the same
#dataset by fliping the image,rotating the image and zooming the image randomly.

data_augment = tf.keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.1,fill_mode="nearest"),
    layers.RandomTranslation(0.002, 0.002, fill_mode="nearest"),
    layers.RandomBrightness(factor=0.15),     # brightness_range=(0.85, 1.15) → factor = ±15%
    layers.RandomContrast(0.15),
    layers.RandomZoom(0.0,fill_mode='nearest'),
    layers.RandomTranslation(0.1, 0.1)
])

"""## Making the CNN Model"""

model = models.Sequential()
model.add(layers.Input(shape=(224,224,3))) #4 -5 layers need to add
#preprocessing layers
model.add(data_augment)
model.add(normalising_layer)
#cnn layers
model.add(layers.Conv2D(16, (4,4), activation='relu',padding='same'))
model.add(layers.MaxPooling2D((2,2)))


model.add(layers.Conv2D(32, (4,4), activation='relu',padding='same'))
model.add(layers.MaxPooling2D((2,2)))


model.add(layers.Conv2D(64, (4,4), activation='relu',padding='same'))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(128, (4,4), activation='relu',padding='same'))
model.add(layers.MaxPooling2D((2,2)))


model.add(layers.Conv2D(256, (4,4), activation='relu',padding='same'))
model.add(layers.MaxPooling2D((2,2)))


#flatten to a vector
model.add(layers.Flatten())
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dropout(0.5,seed=111))
model.add(layers.Dense(4, activation='softmax'))

#compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, beta_1=0.869, beta_2=0.995)
model.compile(optimizer=optimizer,
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

"""## Model layer details"""

model.summary()

"""## Model Training"""

# Training
model_es = EarlyStopping(monitor='loss', min_delta=1e-9, patience=8, verbose=True)
model_rlr = ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=5, verbose=True)

history = model.fit(train_ds, epochs=40,
                    validation_data=validation_ds,
                    callbacks=[model_es,model_rlr])
#validation
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

# Evaluate on test dataset
test_loss, test_acc = model.evaluate(test_ds)
print(f"Test Accuracy: {test_acc:0.5f}")
print(f"Test Loss: {test_loss:0.5f}")

"""## Visualising Prediction"""

# Get class names from the dataset
class_names = train_ds.class_names
print("Class names:", class_names)

for images, labels in test_ds.take(1):
    pred_probs = model.predict(images)
    pred_labels = np.argmax(pred_probs, axis=1)

    plt.figure(figsize=(12, 12))
    num_images = 20  # how many to show

    for i in range(num_images):
        ax = plt.subplot(4,5 , i + 1)

        img = images[i].numpy().astype("uint8")
        true_idx = labels[i].numpy()
        pred_idx = pred_labels[i]

        plt.imshow(img)

        title = f"Pred: {class_names[pred_idx]}\nTrue: {class_names[true_idx]}"
        color = "green" if pred_idx == true_idx else "red"

        plt.title(title, color=color, fontsize=9)
        plt.axis("off")

    plt.tight_layout()
    plt.show()
    break

"""## Confusion Matrix"""

# Extracting the true and prediction labels from the test dataset
all_true = []
all_pred = []

for images, labels in test_ds:
    probs = model.predict(images, verbose=0)
    preds = np.argmax(probs, axis=1)

    all_true.extend(labels.numpy())
    all_pred.extend(preds)

all_true = np.array(all_true)
all_pred = np.array(all_pred)

#Generating the confusion matrix
conf_matrix = confusion_matrix(all_true, all_pred)

#Plot the matrix
display = ConfusionMatrixDisplay(confusion_matrix=conf_matrix,
                              display_labels=train_ds.class_names)

plt.figure(figsize=(6,6))
display.plot(cmap="Blues", values_format='d')
plt.title("Confusion Matrix")
plt.show()

#printing total accuracy and recall
report = classification_report(
    all_true,
    all_pred,
    target_names=train_ds.class_names,
    output_dict=True
)

for cls in train_ds.class_names:
    print(f"\nClass: {cls}")
    print(f"  Precision: {report[cls]['precision']:.4f}")
    print(f"  Recall:    {report[cls]['recall']:.4f}")

"""## Visualise the Feature Map"""

for images, labels in train_ds.take(1):
    _ = model(images)
    break

# Find the first Conv2D layer in your model
conv_layers = [layer for layer in model.layers if isinstance(layer, tf.keras.layers.Conv2D)]
first_conv = conv_layers[0]

print("First conv layer:", first_conv.name, first_conv.output.shape)

# Build a new model: input → output of first conv layer
input_tensor_for_feature_model = model.layers[0].output

#chain the layers that precede the first Conv2D layer
x = model.layers[1](input_tensor_for_feature_model)
x = model.layers[2](x)
output_of_first_conv = model.layers[3](x)

feature_model = tf.keras.Model(inputs=input_tensor_for_feature_model, outputs=output_of_first_conv)

for images, labels in test_ds.take(1):
    sample_img = images[0]
    sample_label = labels[0].numpy()
    break

img_batch = tf.expand_dims(sample_img, axis=0)


feature_maps = feature_model.predict(img_batch)
print("Feature maps shape:", feature_maps.shape)

# Displaying the filters
plt.figure(figsize=(4, 4))
plt.imshow(sample_img.numpy().astype("uint8"))
plt.title(f"Original ({train_ds.class_names[sample_label]})")
plt.axis("off")
plt.show()


fmaps = feature_maps[0]

num_filters_to_show = min(fmaps.shape[-1], 12)
grid_size = int(np.ceil(np.sqrt(num_filters_to_show)))

plt.figure(figsize=(12, 12))
for i in range(num_filters_to_show):
    ax = plt.subplot(grid_size, grid_size, i + 1)
    plt.imshow(fmaps[:, :, i], cmap="gray")
    plt.axis("off")
    plt.title(f"Filter {i}", fontsize=8)

plt.tight_layout()
plt.show()

"""## Predict images"""

def predict_image(model, img_path, class_names):
    # 1. Read model input shape
    _, img_h, img_w, channels = model.input_shape
    color_mode = 'grayscale' if channels == 1 else 'rgb'
    img = image.load_img(img_path,
                         color_mode=color_mode,
                         target_size=(img_h, img_w))
    img_array = image.img_to_array(img)

    if channels == 1 and img_array.shape[-1] == 3:
        # RGB -> grayscale
        img_array = tf.image.rgb_to_grayscale(img_array)
    elif channels == 3 and img_array.shape[-1] == 1:
        # grayscale -> RGB
        img_array = tf.image.grayscale_to_rgb(img_array)

    img_batch = np.expand_dims(img_array, axis=0)

    #Predict
    preds = model.predict(img_batch)
    probs = preds[0]

    #Get predicted class
    pred_index = np.argmax(probs)
    pred_class = class_names[pred_index]

    #Print probabilities
    print("\nClass probabilities:")
    for cls, p in zip(class_names, probs):
        print(f"  {cls:10} : {p*100:.2f}%")

    print("\nFinal Prediction:", pred_class)

    img_to_show = img_array.squeeze()

    if channels == 1:
       plt.imshow(img_to_show, cmap='gray')
    else:
       plt.imshow(img_to_show.astype("uint8"))
    plt.title(f"Prediction: {pred_class}")
    plt.axis("off")
    plt.show()

    return pred_class, probs
pred_class, probs = predict_image(model, "/content/meningioma_test.jpeg", class_names)
pred_class, probs = predict_image(model, "/content/glioma_test.jpeg", class_names)